/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ClienteDAO;
import DAO.ContaDAO;
import POO.Cliente;
import POO.Conta;
import javax.swing.JOptionPane;

/**
 *
 * @author ellen.salicani
 */
public class spaceDeposito extends javax.swing.JFrame {
    private final Conta conta = new Conta();
    private final Cliente cliente = new Cliente();
    private final ContaDAO contaDAO = new ContaDAO();
    private final ClienteDAO clienteDAO = new ClienteDAO();

    /**
     * Creates new form spaceDeposito
     */
    public spaceDeposito() {
        initComponents();
        String saldo = Float.toString(conta.getSaldo());
        jLabel20.setText(saldo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nomeFavorecido = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        valorDeposito = new javax.swing.JFormattedTextField();
        numConta = new javax.swing.JFormattedTextField();
        kButton1 = new keeptoo.KButton();
        jLabel9 = new javax.swing.JLabel();
        numAgencia = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jpDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Saldo:");
        jpDashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Realizar Depósito");
        jpDashboard.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/rocketIcon40x40.png"))); // NOI18N
        jpDashboard.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Valor");
        jpDashboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 50, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Número Conta");
        jpDashboard.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 100, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jpDashboard.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, 20));
        jpDashboard.add(nomeFavorecido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Nome do Favorecido");
        jpDashboard.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, 30));

        valorDeposito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jpDashboard.add(valorDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 140, 40));

        numConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jpDashboard.add(numConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 90, 40));

        kButton1.setText("Depositar");
        kButton1.setkEndColor(new java.awt.Color(22, 22, 67));
        kButton1.setkHoverEndColor(new java.awt.Color(22, 22, 67));
        kButton1.setkHoverForeGround(new java.awt.Color(22, 22, 67));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton1.setkSelectedColor(new java.awt.Color(22, 255, 189));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jpDashboard.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 375, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Agência");
        jpDashboard.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 50, 30));

        numAgencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jpDashboard.add(numAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/backgroundSPACEBANKWithoutRocket.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        Conta contaFavorecido = new Conta();
        Conta conta = new Conta();

        contaFavorecido.setAgencia((int) numAgencia.getValue());
        contaFavorecido.setIdConta((int) numConta.getValue());
        //verificar no banco se o id corresponde
        conta.setIdTipoTransacao(8);
        conta.setValorTotalCompra((double) valorDeposito.getValue());
        conta.setSaldo(conta.getSaldo() - (float) valorDeposito.getValue());
        contaFavorecido.setSaldo(contaFavorecido.getSaldo() + (float) valorDeposito.getValue());
        if(conta.getSaldo() <= 0){
            JOptionPane.showMessageDialog(this, "Saldo insuficiente", "Alerta",
                JOptionPane.WARNING_MESSAGE);
        } else{
            try{
                contaDAO.deposito(conta, contaFavorecido);
                JOptionPane.showMessageDialog(this, "Deposito realizado com sucesso", "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch(Exception e){
                JOptionPane.showMessageDialog(this, "ERRO: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spaceDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spaceDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spaceDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spaceDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spaceDeposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpDashboard;
    private keeptoo.KButton kButton1;
    private javax.swing.JTextField nomeFavorecido;
    private javax.swing.JFormattedTextField numAgencia;
    private javax.swing.JFormattedTextField numConta;
    private javax.swing.JFormattedTextField valorDeposito;
    // End of variables declaration//GEN-END:variables
}
