/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author UserSoffti
 */
public class spaceDeleteAccount extends javax.swing.JFrame {

    /**
     * Creates new form spaceDeleteAccount
     */
    public spaceDeleteAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JPanel();
        lblContinuar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        lblCancelar = new javax.swing.JLabel();
        jpSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jpDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/sadVectorDeleteAccount.png"))); // NOI18N
        jpDashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 60, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("SpaceConta");
        jpDashboard.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/rocketIcon40x40.png"))); // NOI18N
        jpDashboard.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        btnConfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContinuar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblContinuar.setForeground(new java.awt.Color(51, 51, 51));
        lblContinuar.setText("Confirmar");
        lblContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContinuarMouseClicked(evt);
            }
        });
        btnConfirmar.add(lblContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 0, -1, 30));

        jpDashboard.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 140, 30));

        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(51, 51, 51));
        lblCancelar.setText("Cancelar");
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        btnCancelar.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 0, -1, 30));

        jpDashboard.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 140, 30));

        jpSenha.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jpSenha.setForeground(new java.awt.Color(153, 153, 153));
        jpSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpSenha.setText("415278");
        jpSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpDashboard.add(jpSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 360, 100));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Se este for mesmo seu desejo");
        jpDashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("digite a senha do cartão");
        jpDashboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        getContentPane().add(jpDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 440, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/spaceActionBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContinuarMouseClicked
        JOptionPane.showMessageDialog(null, "Conta excluída com sucesso!");
        spaceDeleteAccount sDelAcc = new spaceDeleteAccount();
        sDelAcc.dispatchEvent(new WindowEvent(sDelAcc, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_lblContinuarMouseClicked

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        JOptionPane.showMessageDialog(null, "Cartão bloqueado temporariamente com sucesso!");
        spaceDeleteAccount sDelAcc = new spaceDeleteAccount();
        sDelAcc.dispatchEvent(new WindowEvent(sDelAcc, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        spaceDeleteAccount sDelAcc = new spaceDeleteAccount();
        sDelAcc.dispatchEvent(new WindowEvent(sDelAcc, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        spaceDeleteAccount sDelAcc = new spaceDeleteAccount();
        sDelAcc.dispatchEvent(new WindowEvent(sDelAcc, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spaceDeleteAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spaceDeleteAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spaceDeleteAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spaceDeleteAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spaceDeleteAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jpDashboard;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblContinuar;
    // End of variables declaration//GEN-END:variables
}
