/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author UserSoffti
 */
public class spacePay extends javax.swing.JFrame {

    /**
     * Creates new form spacePay
     */
    public spacePay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfNome = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        tfValor = new javax.swing.JFormattedTextField();
        btnContinuar = new javax.swing.JPanel();
        lblContinuar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        lblCancelar = new javax.swing.JLabel();
        tfCodigodeBarras = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jpDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Digite o código de barras");
        jpDashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("SpaceConta");
        jpDashboard.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/rocketIcon40x40.png"))); // NOI18N
        jpDashboard.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Nome impresso:");
        jpDashboard.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        jpDashboard.add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 220, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Valor:");
        jpDashboard.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        tfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jpDashboard.add(tfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 220, -1));

        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinuarMouseClicked(evt);
            }
        });
        btnContinuar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContinuar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblContinuar.setForeground(new java.awt.Color(51, 51, 51));
        lblContinuar.setText("Continuar");
        lblContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContinuarMouseClicked(evt);
            }
        });
        btnContinuar.add(lblContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 0, -1, 30));

        jpDashboard.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 140, 30));

        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(51, 51, 51));
        lblCancelar.setText("Cancelar");
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        btnCancelar.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 0, -1, 30));

        jpDashboard.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 140, 30));

        tfCodigodeBarras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tfCodigodeBarras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCodigodeBarras.setText("0000000.000000.00000.000000.00000");
        tfCodigodeBarras.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfCodigodeBarras.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        tfCodigodeBarras.setOpaque(false);
        jpDashboard.add(tfCodigodeBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 340, 80));

        getContentPane().add(jpDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 440, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/spaceActionBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinuarMouseClicked
        spaceConfirmPayment sConPay = new spaceConfirmPayment();
        sConPay.setVisible(true);
    }//GEN-LAST:event_btnContinuarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        spacePay sPay = new spacePay();
        sPay.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        spacePay sPay = new spacePay();
        sPay.setVisible(false);
        dispose();
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void lblContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContinuarMouseClicked
        spaceConfirmPayment sConPay = new spaceConfirmPayment();
        sConPay.setVisible(true);
    }//GEN-LAST:event_lblContinuarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spacePay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spacePay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spacePay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spacePay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spacePay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jpDashboard;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblContinuar;
    private javax.swing.JFormattedTextField tfCodigodeBarras;
    private javax.swing.JFormattedTextField tfNome;
    private javax.swing.JFormattedTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
