/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ClienteDAO;
import DAO.ContaDAO;
import POO.Cliente;
import POO.Conta;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author UserSoffti
 */
public class spaceCadastro extends javax.swing.JFrame {
    
    private Cliente cliente = new Cliente();
    private Conta conta = new Conta();
    private ClienteDAO clienteDAO = new ClienteDAO();
    private ContaDAO contaDAO = new ContaDAO();
        
    /**
     * Creates new form spaceCadastro
     */
    public spaceCadastro() {
        initComponents();
    }
    
     private boolean validarFormulario(){
         String senha1 = new String(tfSenha.getPassword());
         String senha2 = new String(tfRepetirSenha.getPassword());
         
         try{
            if(tfEmail.getText().trim().length() < 2){
              JOptionPane.showMessageDialog(this, "Nome inválido", "Alerta",
              JOptionPane.WARNING_MESSAGE);
              return false;
          }

             if(tfIdade.getText().trim().length() < 2){
                  JOptionPane.showMessageDialog(this, "Idade inválida", "Alerta",
                  JOptionPane.WARNING_MESSAGE);
                  return false;
              }
              if(tfCpfCnpj.getText().trim().length() < 14){
                  JOptionPane.showMessageDialog(this, "CPF inválido", "Alerta",
                  JOptionPane.WARNING_MESSAGE);
                  return false;
              }
              if(tfEmail.getText().trim().length() < 10){
                  JOptionPane.showMessageDialog(this, "E-Mail inválido", "Alerta",
                  JOptionPane.WARNING_MESSAGE);
                  return false;
              }
              if(tfSenha.getPassword().length <  8 || tfSenha.getPassword().length > 16){
                  JOptionPane.showMessageDialog(this, "Senha deve conter entre 8 até 16 caracteres", "Alerta",
                  JOptionPane.WARNING_MESSAGE);
                  return false;
              }
                if(tfRepetirSenha.getPassword().length  <  8 || tfRepetirSenha.getPassword().length > 16){
                  JOptionPane.showMessageDialog(this, "Senha deve conter entre 8 até 16 caracteres", "Alerta",
                  JOptionPane.WARNING_MESSAGE);
                  return false;
              }
                
                if (!(senha2).equals(senha1)) {
                    System.out.println(senha2);
                    System.out.println(senha1);
                    
                         JOptionPane.showMessageDialog(null, "Senhas não são compatíveis.", "Alerta", 
                         JOptionPane.ERROR_MESSAGE);
                    return false;
                }   
         return true;
         } catch(Exception e){
             JOptionPane.showMessageDialog(this, "Algo aconteceu: " + e.getMessage(), "Alerta", JOptionPane.ERROR_MESSAGE);
             return false;
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoDeConta = new javax.swing.ButtonGroup();
        btnGroupPfPj = new javax.swing.ButtonGroup();
        cadastroTitulo = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblCpfCnpj = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        tfRepetirSenha = new javax.swing.JPasswordField();
        tipoPoupanca = new javax.swing.JRadioButton();
        tipoCorrente = new javax.swing.JRadioButton();
        pessoaJuridica = new javax.swing.JRadioButton();
        pessoaFisica = new javax.swing.JRadioButton();
        tfIdade = new javax.swing.JFormattedTextField();
        lblTipoConta = new javax.swing.JLabel();
        tfCpfCnpj = new javax.swing.JTextField();
        lblNomeCompleto = new javax.swing.JLabel();
        lblrepetirSenha = new javax.swing.JLabel();
        tfNomeCompleto = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bgTelaImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastroTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cadastroTitulo.setForeground(new java.awt.Color(255, 255, 255));
        cadastroTitulo.setText("Cadastro de Pessoas");
        getContentPane().add(cadastroTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        lblIdade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(255, 255, 255));
        lblIdade.setText("idade:");
        getContentPane().add(lblIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 70, 20));

        lblCpfCnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCpfCnpj.setForeground(new java.awt.Color(255, 255, 255));
        lblCpfCnpj.setText("CPF/CNPJ:");
        getContentPane().add(lblCpfCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 110, -1));

        tfSenha.setBackground(new java.awt.Color(22, 22, 67));
        tfSenha.setColumns(8);
        tfSenha.setForeground(new java.awt.Color(255, 255, 255));
        tfSenha.setToolTipText("Minimo 6, máximo 8 digitos");
        tfSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tfSenha.setOpaque(false);
        getContentPane().add(tfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 160, 30));

        tfRepetirSenha.setBackground(new java.awt.Color(22, 22, 67));
        tfRepetirSenha.setColumns(8);
        tfRepetirSenha.setForeground(new java.awt.Color(255, 255, 255));
        tfRepetirSenha.setToolTipText("Minimo 6, máximo 8 digitos");
        tfRepetirSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tfRepetirSenha.setOpaque(false);
        getContentPane().add(tfRepetirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 170, 30));

        tipoPoupanca.setBackground(new java.awt.Color(21, 22, 68));
        btnGroupTipoDeConta.add(tipoPoupanca);
        tipoPoupanca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoPoupanca.setForeground(new java.awt.Color(255, 255, 255));
        tipoPoupanca.setText("Poupança");
        getContentPane().add(tipoPoupanca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        tipoCorrente.setBackground(new java.awt.Color(21, 22, 68));
        btnGroupTipoDeConta.add(tipoCorrente);
        tipoCorrente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoCorrente.setForeground(new java.awt.Color(255, 255, 255));
        tipoCorrente.setSelected(true);
        tipoCorrente.setText("Corrente");
        getContentPane().add(tipoCorrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        pessoaJuridica.setBackground(new java.awt.Color(21, 22, 68));
        btnGroupPfPj.add(pessoaJuridica);
        pessoaJuridica.setForeground(new java.awt.Color(255, 255, 255));
        pessoaJuridica.setText("Pessoa Jurídica");
        getContentPane().add(pessoaJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        pessoaFisica.setBackground(new java.awt.Color(21, 22, 68));
        btnGroupPfPj.add(pessoaFisica);
        pessoaFisica.setForeground(new java.awt.Color(255, 255, 255));
        pessoaFisica.setText("Pessoa Física");
        getContentPane().add(pessoaFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        tfIdade.setBackground(new java.awt.Color(22, 22, 67));
        tfIdade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tfIdade.setForeground(new java.awt.Color(255, 255, 255));
        tfIdade.setOpaque(false);
        getContentPane().add(tfIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 90, 30));

        lblTipoConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTipoConta.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoConta.setText("tipo de conta:");
        getContentPane().add(lblTipoConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 140, -1));

        tfCpfCnpj.setBackground(new java.awt.Color(22, 22, 67));
        tfCpfCnpj.setForeground(new java.awt.Color(255, 255, 255));
        tfCpfCnpj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        getContentPane().add(tfCpfCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 220, 30));

        lblNomeCompleto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeCompleto.setText("nome completo:");
        getContentPane().add(lblNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 130, -1));

        lblrepetirSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblrepetirSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblrepetirSenha.setText("repetir senha:");
        getContentPane().add(lblrepetirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 140, -1));

        tfNomeCompleto.setBackground(new java.awt.Color(22, 22, 67));
        tfNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        tfNomeCompleto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        getContentPane().add(tfNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 330, 30));

        tfEmail.setBackground(new java.awt.Color(22, 22, 67));
        tfEmail.setForeground(new java.awt.Color(255, 255, 255));
        tfEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 330, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("e-mail:");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 110, -1));
        lblEmail.getAccessibleContext().setAccessibleName("lblEmail");

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("senha:");
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 110, -1));

        btnCadastro.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 130, 30));

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setForeground(new java.awt.Color(22, 22, 67));
        btnCadastrar.setToolTipText("Cadastrar");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnCadastrarLayout = new javax.swing.GroupLayout(btnCadastrar);
        btnCadastrar.setLayout(btnCadastrarLayout);
        btnCadastrarLayout.setHorizontalGroup(
            btnCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        btnCadastrarLayout.setVerticalGroup(
            btnCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 130, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgTelaImg.setBackground(new java.awt.Color(22, 22, 67));
        bgTelaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/backgroundSPACEBANK.png"))); // NOI18N
        bgTelaImg.setPreferredSize(new java.awt.Dimension(479, 500));
        jPanel1.add(bgTelaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 478, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        
         String senha1 = new String(tfSenha.getPassword());
         String cpfCnpj = tfCpfCnpj.getText();
         String nome = tfNomeCompleto.getText();
         String email = tfEmail.getText();
         Boolean pfpj = pessoaFisica.isSelected();
         
         
         if(validarFormulario()){   
             //TO DO: VER COM O PROFESSOR O QUE TEM QUE FAZER AQUI 
            if(true){
                System.out.println(cpfCnpj);
                System.out.println(pfpj);
                cliente.setCpfCnpj(cpfCnpj);
                cliente.setIdade(Integer.parseInt(tfIdade.getText()));  
                cliente.setEmail(email);
                cliente.setSenha(senha1);
                cliente.setNomeCompleto(nome);
                cliente.setPessoaFisica(pessoaFisica.isSelected());
                try{
                    
                    clienteDAO.inserir(cliente);
//                    contaDAO.inserir(conta);
                     JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso. Seja bem vindo(a)!"
                    , "OK", JOptionPane.INFORMATION_MESSAGE);
                     spaceUserArea sua = new spaceUserArea();
                     sua.setVisible(true);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this, "Erro ao inserir cliente."
                    + "\n" +ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }else{
               
                    JOptionPane.showMessageDialog(this, "Cliente já existe"
                    + "\n" , "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spaceCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spaceCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spaceCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spaceCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spaceCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgTelaImg;
    private javax.swing.JPanel btnCadastrar;
    private javax.swing.JButton btnCadastro;
    private javax.swing.ButtonGroup btnGroupPfPj;
    private javax.swing.ButtonGroup btnGroupTipoDeConta;
    private javax.swing.JLabel cadastroTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipoConta;
    private javax.swing.JLabel lblrepetirSenha;
    private javax.swing.JRadioButton pessoaFisica;
    private javax.swing.JRadioButton pessoaJuridica;
    private javax.swing.JTextField tfCpfCnpj;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JFormattedTextField tfIdade;
    private javax.swing.JTextField tfNomeCompleto;
    private javax.swing.JPasswordField tfRepetirSenha;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JRadioButton tipoCorrente;
    private javax.swing.JRadioButton tipoPoupanca;
    // End of variables declaration//GEN-END:variables
}
