/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author UserSoffti
 */
public class spaceUserArea extends javax.swing.JFrame {

    /**
     * Creates new form spaceUserArea
     */
    public spaceUserArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAcoes = new javax.swing.JMenu();
        jMenuSaldo = new javax.swing.JMenuItem();
        jMenuTransferir = new javax.swing.JMenuItem();
        jMenuPagar = new javax.swing.JMenuItem();
        jMenuCartaoVirtual = new javax.swing.JMenuItem();
        jMenuSeguranca = new javax.swing.JMenu();
        jMenuBloquearCartao = new javax.swing.JMenuItem();
        jMenuExcluirConta = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/spaceUserArea1280x720.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jMenuBar1.setOpaque(false);

        jMenuAcoes.setText("Ações");

        jMenuSaldo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuSaldo.setText("Consultar Saldo");
        jMenuSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaldoActionPerformed(evt);
            }
        });
        jMenuAcoes.add(jMenuSaldo);

        jMenuTransferir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuTransferir.setText("Transferir");
        jMenuTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTransferirActionPerformed(evt);
            }
        });
        jMenuAcoes.add(jMenuTransferir);

        jMenuPagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuPagar.setText("Pagar");
        jMenuPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPagarActionPerformed(evt);
            }
        });
        jMenuAcoes.add(jMenuPagar);

        jMenuCartaoVirtual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuCartaoVirtual.setText("Cartão Virtual");
        jMenuCartaoVirtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCartaoVirtualActionPerformed(evt);
            }
        });
        jMenuAcoes.add(jMenuCartaoVirtual);

        jMenuBar1.add(jMenuAcoes);

        jMenuSeguranca.setText("Segurança");

        jMenuBloquearCartao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuBloquearCartao.setText("Bloquear Cartão");
        jMenuBloquearCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBloquearCartaoActionPerformed(evt);
            }
        });
        jMenuSeguranca.add(jMenuBloquearCartao);

        jMenuExcluirConta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuExcluirConta.setText("Excluir Conta");
        jMenuExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExcluirContaActionPerformed(evt);
            }
        });
        jMenuSeguranca.add(jMenuExcluirConta);

        jMenuBar1.add(jMenuSeguranca);

        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSobre);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        spaceAbout sAbout = new spaceAbout();
        sAbout.setVisible(true);
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jMenuSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaldoActionPerformed
        spaceBalance sBalance = new spaceBalance();
        sBalance.setVisible(true);
    }//GEN-LAST:event_jMenuSaldoActionPerformed

    private void jMenuTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTransferirActionPerformed
        spaceTransfer sTransfer = new spaceTransfer();
        sTransfer.setVisible(true);
    }//GEN-LAST:event_jMenuTransferirActionPerformed

    private void jMenuPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPagarActionPerformed
       spacePay sPay = new spacePay();
       sPay.setVisible(true);
    }//GEN-LAST:event_jMenuPagarActionPerformed

    private void jMenuCartaoVirtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCartaoVirtualActionPerformed
        spaceVirtualCard sVirCard = new spaceVirtualCard();
        sVirCard.setVisible(true);
    }//GEN-LAST:event_jMenuCartaoVirtualActionPerformed

    private void jMenuBloquearCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBloquearCartaoActionPerformed
        spaceBlockCard sBlockCard = new spaceBlockCard();
        sBlockCard.setVisible(true);
    }//GEN-LAST:event_jMenuBloquearCartaoActionPerformed

    private void jMenuExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExcluirContaActionPerformed
        spaceDeleteAccount sDelAcc = new spaceDeleteAccount();
        sDelAcc.setVisible(true);
    }//GEN-LAST:event_jMenuExcluirContaActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spaceUserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spaceUserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spaceUserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spaceUserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spaceUserArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAcoes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBloquearCartao;
    private javax.swing.JMenuItem jMenuCartaoVirtual;
    private javax.swing.JMenuItem jMenuExcluirConta;
    private javax.swing.JMenuItem jMenuPagar;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenuItem jMenuSaldo;
    private javax.swing.JMenu jMenuSeguranca;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenuItem jMenuTransferir;
    // End of variables declaration//GEN-END:variables
}
