/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.ADM;

/**
 *
 * @author UserSoffti
 */
public class spaceFindUsers extends javax.swing.JFrame {

    /**
     * Creates new form spaceFindUsers
     */
    public spaceFindUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tfAgencia = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfUserId = new javax.swing.JFormattedTextField();
        tfCpfCnpj = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        tfConta = new javax.swing.JFormattedTextField();
        btnExcluir = new javax.swing.JPanel();
        lblExcluir = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JPanel();
        lblAtualizar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 760, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Endereço:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 110, -1));

        tfEndereco.setBackground(new java.awt.Color(22, 22, 67));
        tfEndereco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tfEndereco.setForeground(new java.awt.Color(255, 255, 255));
        tfEndereco.setOpaque(false);
        getContentPane().add(tfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 280, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agência:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 110, -1));

        tfAgencia.setBackground(new java.awt.Color(22, 22, 67));
        tfAgencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tfAgencia.setForeground(new java.awt.Color(255, 255, 255));
        tfAgencia.setOpaque(false);
        getContentPane().add(tfAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 280, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 90, -1));

        tfSenha.setBackground(new java.awt.Color(22, 22, 67));
        tfSenha.setForeground(new java.awt.Color(255, 255, 255));
        tfSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tfSenha.setOpaque(false);
        getContentPane().add(tfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 280, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CPF/CNPJ:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("UserID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 110, -1));

        tfUserId.setBackground(new java.awt.Color(22, 22, 67));
        tfUserId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tfUserId.setForeground(new java.awt.Color(255, 255, 255));
        tfUserId.setOpaque(false);
        getContentPane().add(tfUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 280, 30));

        tfCpfCnpj.setBackground(new java.awt.Color(22, 22, 67));
        tfCpfCnpj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tfCpfCnpj.setForeground(new java.awt.Color(255, 255, 255));
        tfCpfCnpj.setOpaque(false);
        getContentPane().add(tfCpfCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 280, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 110, -1));

        tfEmail.setBackground(new java.awt.Color(22, 22, 67));
        tfEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tfEmail.setForeground(new java.awt.Color(255, 255, 255));
        tfEmail.setOpaque(false);
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 280, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Conta:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 110, -1));

        tfConta.setBackground(new java.awt.Color(22, 22, 67));
        tfConta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        tfConta.setForeground(new java.awt.Color(255, 255, 255));
        tfConta.setOpaque(false);
        getContentPane().add(tfConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 280, 30));

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setForeground(new java.awt.Color(22, 22, 67));
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExcluir.setForeground(new java.awt.Color(22, 22, 67));
        lblExcluir.setText("Excluir");
        btnExcluir.add(lblExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 11, -1, -1));

        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 90, 140, 40));

        btnAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setForeground(new java.awt.Color(22, 22, 67));
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAtualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAtualizar.setForeground(new java.awt.Color(22, 22, 67));
        lblAtualizar.setText("Alterar");
        lblAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.add(lblAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 11, -1, -1));

        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/spaceAdmArea.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spaceFindUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spaceFindUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spaceFindUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spaceFindUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spaceFindUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAtualizar;
    private javax.swing.JPanel btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAtualizar;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JFormattedTextField tfAgencia;
    private javax.swing.JFormattedTextField tfConta;
    private javax.swing.JFormattedTextField tfCpfCnpj;
    private javax.swing.JFormattedTextField tfEmail;
    private javax.swing.JFormattedTextField tfEndereco;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JFormattedTextField tfUserId;
    // End of variables declaration//GEN-END:variables
}
