/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.ADM;
import GUI.spaceAbout;
import GUI.spaceCadastro;
import POO.Admin;

/**
 *
 * @author UserSoffti
 */
public class spaceAdmArea extends javax.swing.JFrame {

    Admin admin;
    
    /**
     * Creates new form spaceAdmArea
     */
    public spaceAdmArea(Admin admin) {
        initComponents();
        this.admin = admin;
    }

    private spaceAdmArea() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuAdm = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCadastroPessoas = new javax.swing.JMenuItem();
        jMenuCadastroAdm = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuConsultarUsuarios = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG/spaceAdmArea.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jMenuAdm.setBackground(new java.awt.Color(255, 255, 255));
        jMenuAdm.setOpaque(false);

        jMenu1.setText("Cadastro");

        jMenuCadastroPessoas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadastroPessoas.setText("Nova Conta");
        jMenuCadastroPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCadastroPessoasMouseClicked(evt);
            }
        });
        jMenuCadastroPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroPessoasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroPessoas);

        jMenuCadastroAdm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadastroAdm.setText("Novo ADM");
        jMenuCadastroAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroAdmActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroAdm);

        jMenuAdm.add(jMenu1);

        jMenu2.setText("Consulta");

        jMenuConsultarUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuConsultarUsuarios.setText("Usuários");
        jMenuConsultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuConsultarUsuarios);

        jMenuAdm.add(jMenu2);

        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuAdm.add(jMenuSobre);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuAdm.add(jMenuSair);

        setJMenuBar(jMenuAdm);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        spaceAbout sa = new spaceAbout();
        sa.setVisible(true);
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jMenuCadastroPessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCadastroPessoasMouseClicked
        spaceCadastro sc = new spaceCadastro();
        sc.setVisible(true);
    }//GEN-LAST:event_jMenuCadastroPessoasMouseClicked

    private void jMenuCadastroAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroAdmActionPerformed
        spaceRegisterAdm regAdm = new spaceRegisterAdm();
        regAdm.setVisible(true);
    }//GEN-LAST:event_jMenuCadastroAdmActionPerformed

    private void jMenuConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarUsuariosActionPerformed
        spaceFindUsers sFind = new spaceFindUsers();
        sFind.setVisible(true);
    }//GEN-LAST:event_jMenuConsultarUsuariosActionPerformed

    private void jMenuCadastroPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroPessoasActionPerformed
        spaceCadastro sCadastro = new spaceCadastro();
        sCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuCadastroPessoasActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
       System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spaceAdmArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spaceAdmArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spaceAdmArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spaceAdmArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spaceAdmArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuAdm;
    private javax.swing.JMenuItem jMenuCadastroAdm;
    private javax.swing.JMenuItem jMenuCadastroPessoas;
    private javax.swing.JMenuItem jMenuConsultarUsuarios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuSobre;
    // End of variables declaration//GEN-END:variables
}
